name: swapu
description: A new Flutter project.
publish_to: 'none' # Private project

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ğŸ”¥ Firebase Core & Auth
  firebase_core: ^2.27.0
  firebase_auth: ^4.20.0

  # â˜ï¸ Firestore & Storage
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.7.2

  # ğŸ“· Gambar dari galeri/kamera
  image_picker: ^1.1.0

  # ğŸ“‚ Path dan akses file lokal
  path: ^1.9.0
  path_provider: ^2.1.2

  # ğŸ”„ Parsing MIME type saat upload
  http_parser: ^4.0.2

  # ğŸŒ (Opsional) Ambil data dari internet
  http: ^0.13.6

  # ğŸ“¢ (Opsional) Notifikasi push
  # firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/swapu.png
